name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  makefile-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make

  cmake-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: actions/run-cmake@v10
